name: Lint Code

on:
  push:
    branches:
      - main  # Run on pushes to the main branch
  pull_request:
    branches:
      - main  # Run on pull requests targeting the main branch

jobs:
  lint:
    name: Lint Codebase
    runs-on: ubuntu-latest

    strategy:
      matrix:
        language: [python, javascript]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python Environment
      if: matrix.language == 'python'
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Python Dependencies
      if: matrix.language == 'python'
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: Run Flake8 Linter (Python)
      if: matrix.language == 'python'
      run: |
        flake8 .

    - name: Set up Node.js Environment
      if: matrix.language == 'javascript'
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install JavaScript Dependencies
      if: matrix.language == 'javascript'
      run: |
        npm install eslint

    - name: Run ESLint Linter (JavaScript)
      if: matrix.language == 'javascript'
      run: |
        npx eslint . --ext .js,.jsx
